Add fromSafeInt and fromSafeString

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -13,6 +13,10 @@ if ! $(cd "$project" && elm-test &>/dev/null); then
   fail "One or more tests failed. Run: elm-test"
 fi
 
+if ! $(cd "$project/examples" && elm-test &>/dev/null); then
+  fail "One or more tests failed. Run: cd \"$project/examples\" && elm-test"
+fi
+
 for main in $(echo "$project/src/*.elm" "$project/examples/src/*.elm"); do
   cd "${main%/src/*.elm}" && elm make "$main" --output=/dev/null || exit 1
 done >/dev/null
